### ISSUE TITLE
[BUG] BandPowerSeriesTransformer error

### ISSUE THREAD

**Issue by TonyBagnall** [aeon-toolkit/aeon-neuro#79]
### Describe the bug

just playing with BandPowerSeriesTransformer @griegner and it throws an error. It may be the series is too short, but if there is a minimum series length requirement it should be more explicit

### Steps/Code to reproduce the bug

```python

    from aeon_neuro.transformations.bandpower import BandPowerSeriesTransformer
    X = np.random.random((32,1000))
    bp = BandPowerSeriesTransformer()
    trans = bp.fit_transform(X)
```

### Expected results

return 
```python
np.ndarray of shape (5_bands, int(n_timepoints/n_per_seg))
```
so (5,4)? Should probably window this

### Actual results

```python-traceback
Traceback (most recent call last):
  File "C:\Code\aeon-neuro\aeon_neuro\examples\example_load_classification_problem_from_raw.py", line 158, in <module>
    trans = bp.fit_transform(X)
  File "C:\Code\aeon-neuro\venv\lib\site-packages\aeon\transformations\series\base.py", line 146, in fit_transform
    Xt = self._fit_transform(X=X, y=y)
  File "C:\Code\aeon-neuro\venv\lib\site-packages\aeon\transformations\series\base.py", line 272, in _fit_transform
    return self._fit(X, y)._transform(X, y)
  File "C:\Code\aeon-neuro\aeon_neuro\transformations\bandpower.py", line 99, in _transform
    band_powers[band_idx, :] = simpson(
  File "C:\Code\aeon-neuro\venv\lib\site-packages\scipy\_lib\deprecation.py", line 213, in inner_f
    return f(*args, **kwargs)
  File "C:\Code\aeon-neuro\venv\lib\site-packages\scipy\integrate\_quadrature.py", line 808, in simpson
    result += alpha*y[slice1] + beta*y[slice2] - eta*y[slice3]
IndexError: index -1 is out of bounds for axis 1 with size 0

Process finished with exit code 1
```

**Comment by TonyBagnall** [comment]
actually probably a problem with shape somewhere, this also crashes

```python
    from aeon_neuro.transformations.bandpower import BandPowerSeriesTransformer
    X = np.random.random((32,10000))
    bp = BandPowerSeriesTransformer()
    trans = bp.fit_transform(X)
```
